volumes:
  db:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 803:80
    volumes:
      - ./site:/var/www/test
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    user: 1000:1000
    working_dir: /var/www/test
    volumes:
      - ./site:/var/www/test
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mgpu_db
      POSTGRES_USER: mgpu
      POSTGRES_PASSWORD: mgpu